name: Deploy Shiny App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SHINYAPPS_NAME: ${{ secrets.SHINYAPPS_NAME }}
      SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
      SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
      SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      R_LIBS_USER: ~/R/library
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/renv.lock') }}
          restore-keys: ${{ runner.os }}-r-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libgit2-dev \
            libfontconfig1-dev \
            libfreetype6-dev \
            libjpeg-dev \
            libpng-dev \
            libtiff-dev \
            libicu-dev \
            libfribidi-dev \
            libharfbuzz-dev \
            pandoc \
            libglpk-dev \
            libgmp3-dev
          
      - name: Install R dependencies
        run: |
          Rscript -e '
          options(repos = c(CRAN = "https://packagemanager.posit.co/cran/__linux__/jammy/latest"))
          install.packages(c(
            "rsconnect",
            "shiny",
            "tidyverse",
            "spotifyr",
            "shinydashboard",
            "plotly",
            "DT",
            "shinyWidgets",
            "waiter",
            "markdown",
            "rmarkdown",
            "knitr"
          ), dependencies=TRUE, Ncpus=2)'
          
      - name: Deploy to shinyapps.io
        run: |
          Rscript -e '
          library(rsconnect)
          rsconnect::setAccountInfo(
            name=Sys.getenv("SHINYAPPS_NAME"),
            token=Sys.getenv("SHINYAPPS_TOKEN"),
            secret=Sys.getenv("SHINYAPPS_SECRET")
          )
          rsconnect::deployApp(
            appName = "spotify-artist-analytics",
            forceUpdate = TRUE
          )' 
