name: Deploy Shiny App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SHINYAPPS_NAME: ${{ secrets.SHINYAPPS_NAME }}
      SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
      SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install pak
        run: |
          Rscript -e 'install.packages("pak", repos = "https://cloud.r-project.org")'
          
      - name: Install R dependencies
        run: |
          Rscript -e '
          if (!require("pak")) install.packages("pak", repos = "https://cloud.r-project.org")
          pak::pkg_install(c(
            "shiny",
            "shinydashboard",
            "tidyverse",
            "DT",
            "plotly",
            "waiter",
            "spotifyr",
            "rsconnect"
          ))'
          
      - name: Deploy to shinyapps.io
        run: |
          Rscript -e '
          library(rsconnect)
          rsconnect::setAccountInfo(
            name=Sys.getenv("SHINYAPPS_NAME"),
            token=Sys.getenv("SHINYAPPS_TOKEN"),
            secret=Sys.getenv("SHINYAPPS_SECRET")
          )
          rsconnect::deployApp(
            appName = "spotify-artist-analytics",
            forceUpdate = TRUE
          )' 
