name: Deploy Shiny App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SHINYAPPS_NAME: ${{ secrets.SHINYAPPS_NAME }}
      SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
      SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
      SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libpng-dev \
            libjpeg-dev \
            libfontconfig1-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libfreetype6-dev \
            libmagick++-dev \
            libgit2-dev \
            libssh2-1-dev \
            zlib1g-dev \
            libbz2-dev \
            liblzma-dev

      - name: Install BiocManager
        run: |
          Rscript -e 'install.packages("BiocManager", repos="http://cran.rstudio.com/")'
          Rscript -e 'BiocManager::install("Biobase")'

      - name: Install R packages
        run: |
          Rscript -e '
          install.packages(c(
            "rsconnect",
            "shiny",
            "tidyverse",
            "spotifyr",
            "shinydashboard",
            "plotly",
            "DT",
            "shinyWidgets",
            "waiter",
            "markdown",
            "dplyr",
            "ggplot2"
          ), dependencies=TRUE, repos="http://cran.rstudio.com/")'
          
      - name: Set environment variables
        run: |
          echo "SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }}" >> $GITHUB_ENV
          echo "SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }}" >> $GITHUB_ENV
          
      - name: Deploy to shinyapps.io
        run: |
          Rscript -e '
          library(rsconnect)
          rsconnect::setAccountInfo(
            name=Sys.getenv("SHINYAPPS_NAME"),
            token=Sys.getenv("SHINYAPPS_TOKEN"),
            secret=Sys.getenv("SHINYAPPS_SECRET")
          )
          rsconnect::deployApp(
            appName = "spotify-artist-analytics",
            forceUpdate = TRUE
          )' 